//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioAlquiler.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBAlquilerVehiculoEntities : DbContext
    {
        public DBAlquilerVehiculoEntities()
            : base("name=DBAlquilerVehiculoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tblAlquiler> tblAlquiler { get; set; }
        public DbSet<tblCargoEmpleado> tblCargoEmpleado { get; set; }
        public DbSet<tblCiudad> tblCiudad { get; set; }
        public DbSet<tblCliente> tblCliente { get; set; }
        public DbSet<tblColor> tblColor { get; set; }
        public DbSet<tblDepartamento> tblDepartamento { get; set; }
        public DbSet<tblDevolucion> tblDevolucion { get; set; }
        public DbSet<tblEmpleado> tblEmpleado { get; set; }
        public DbSet<tblGama> tblGama { get; set; }
        public DbSet<tblLicencia> tblLicencia { get; set; }
        public DbSet<tblMarca> tblMarca { get; set; }
        public DbSet<tblPais> tblPais { get; set; }
        public DbSet<tblSede> tblSede { get; set; }
        public DbSet<tblTelefonoCliente> tblTelefonoCliente { get; set; }
        public DbSet<tblTipoDocumento> tblTipoDocumento { get; set; }
        public DbSet<tblTipoTelefono> tblTipoTelefono { get; set; }
        public DbSet<tblTipoVehiculo> tblTipoVehiculo { get; set; }
        public DbSet<tblVehiculo> tblVehiculo { get; set; }
    }
}
