//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioAlquiler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAlquiler
    {
        public tblAlquiler()
        {
            this.tblDevolucion = new HashSet<tblDevolucion>();
        }
    
        public int Codigo { get; set; }
        public string CedulaCliente { get; set; }
        public string IDEmpleado { get; set; }
        public string PlacaVehiculo { get; set; }
        public string EstadoAlquiler { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
    
        public virtual tblCliente tblCliente { get; set; }
        public virtual tblEmpleado tblEmpleado { get; set; }
        public virtual tblVehiculo tblVehiculo { get; set; }
        public virtual ICollection<tblDevolucion> tblDevolucion { get; set; }
    }
}
