//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioAlquiler.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    public partial class tblDepartamento
    {
        public tblDepartamento()
        {
            this.tblCiudads = new HashSet<tblCiudad>();
        }
    
        public int Codigo { get; set; }
        public string Nombre { get; set; }
        public bool Activo { get; set; }
        public int IDPais { get; set; }

        [JsonIgnore]
        [IgnoreDataMember]
        public virtual ICollection<tblCiudad> tblCiudads { get; set; }
        [JsonIgnore]
        [IgnoreDataMember]
        public virtual tblPai tblPai { get; set; }
    }
}
