//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioAlquiler.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    public partial class tblEmpleado
    {
        public tblEmpleado()
        {
            this.tblAlquilers = new HashSet<tblAlquiler>();
            this.tblDevolucions = new HashSet<tblDevolucion>();
        }
    
        public string Documento { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public int IDCargoEmpleado { get; set; }

        [JsonIgnore]
        [IgnoreDataMember]
        public virtual ICollection<tblAlquiler> tblAlquilers { get; set; }
        [JsonIgnore]
        [IgnoreDataMember]
        public virtual tblCargoEmpleado tblCargoEmpleado { get; set; }
        [JsonIgnore]
        [IgnoreDataMember]
        public virtual ICollection<tblDevolucion> tblDevolucions { get; set; }
    }
}
