//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioAlquiler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLicencia
    {
        public tblLicencia()
        {
            this.tblCliente = new HashSet<tblCliente>();
        }
    
        public int Codigo { get; set; }
        public string CategoriaLicencia { get; set; }
    
        public virtual ICollection<tblCliente> tblCliente { get; set; }
    }
}
