//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioAlquiler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVehiculo
    {
        public tblVehiculo()
        {
            this.tblAlquiler = new HashSet<tblAlquiler>();
        }
    
        public string Placa { get; set; }
        public string Descripcion { get; set; }
        public string Estado { get; set; }
        public int IDSede { get; set; }
        public int IDMarca { get; set; }
        public int IDGama { get; set; }
        public int IDColor { get; set; }
        public int Precio { get; set; }
        public int IDTipoVehiculo { get; set; }
    
        public virtual ICollection<tblAlquiler> tblAlquiler { get; set; }
        public virtual tblColor tblColor { get; set; }
        public virtual tblGama tblGama { get; set; }
        public virtual tblMarca tblMarca { get; set; }
        public virtual tblSede tblSede { get; set; }
        public virtual tblTipoVehiculo tblTipoVehiculo { get; set; }
    }
}
