//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioAlquiler.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    public partial class tblVehiculo
    {
        public tblVehiculo()
        {
            this.tblAlquilers = new HashSet<tblAlquiler>();
            this.tblReservars = new HashSet<tblReservar>();
        }
    
        public string Placa { get; set; }
        public string Descripcion { get; set; }
        public string Estado { get; set; }
        public int IDSede { get; set; }
        public int IDMarca { get; set; }
        public int IDGama { get; set; }
        public int IDColor { get; set; }
        public int Precio { get; set; }
        public int IDTipoVehiculo { get; set; }

        [JsonIgnore]
        [IgnoreDataMember]
        public virtual ICollection<tblAlquiler> tblAlquilers { get; set; }
        [JsonIgnore]
        [IgnoreDataMember]
        public virtual tblColor tblColor { get; set; }
        [JsonIgnore]
        [IgnoreDataMember]
        public virtual tblGama tblGama { get; set; }
        [JsonIgnore]
        [IgnoreDataMember]
        public virtual tblMarca tblMarca { get; set; }
        [JsonIgnore]
        [IgnoreDataMember]
        public virtual ICollection<tblReservar> tblReservars { get; set; }
        [JsonIgnore]
        [IgnoreDataMember]
        public virtual tblSede tblSede { get; set; }
        [JsonIgnore]
        [IgnoreDataMember]
        public virtual tblTipoVehiculo tblTipoVehiculo { get; set; }
    }
}
